### ISSUE TITLE
@EnableBulkApi failing in spring boot

### ISSUE THREAD

**Issue by handyccc** [wnameless/spring-bulk-api#3]
When I add the following class to my spring boot application:

```
@Configuration
@EnableBulkApi
public class WebConfig {

}

```

Then I get the following error on startup:

`o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'com.github.wnameless.spring.bulkapi.BulkApiConfig' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'`

Any ideas what I'm doing wrong?

**Comment by wnameless** [comment]
Can you provide your spring boot version?

**Comment by handyccc** [comment]
Sure, it is 2.0.0.M4

**Comment by wnameless** [comment]
I will run some tests under spring boot version 2.0.0. After all, it's quite new.

**Comment by handyccc** [comment]
ok, i upgraded to 2.0.0.Release and still have the same issue

**Comment by handyccc** [comment]
How did your tests go with spring boot version 2.0.0?

**Comment by wnameless** [comment]
The tests are all passed...

Can you provide your minimal pom file and test codes, which reproduces this issue?

**Comment by handyccc** [comment]
Hi, sure - I created a new empty spring boot project (I'm using gradle for the build instead of maven) and added the spring-bulk-api and the @EnableBulkApi annotation to a WebConfig class.

When i attempt to run with "gradle clean bootRun"  I still get the error:

o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'com.github.wnameless.spring.bulkapi.BulkApiConfig' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.


Attaching the test project:

[bulktester.zip](https://github.com/wnameless/spring-bulk-api/files/1792744/bulktester.zip)

**Comment by wnameless** [comment]
I just made an update to this project and the new version is v0.6.0. So far, everything is fine.
I provide you an simple maven project example here:
[spring-bulk-api-demo.zip](https://github.com/wnameless/spring-bulk-api/files/1796240/spring-bulk-api-demo.zip)

After application started, run the following command to test with it:
curl -H "Content-Type: application/json" -X POST -d '{"operations":[ {"method": "GET", "url": "/index"}  ]}' http://localhost:8080/bulk

**Comment by handyccc** [comment]
yes, that fixed it and it works on my project as well, thank you!
