### ISSUE TITLE
Doesn't work with a server.context-path configured

### ISSUE THREAD

**Issue by asterion9** [wnameless/spring-bulk-api#6]
If my server is configured with a context path, either the specified service url is filtered by the BulkApiValidator (in RoutingPathResolver#findByRequestPathAndMethod) when sent with the context path, or the url is malformed by [DefaultBulkApiService#computeUri](https://github.com/wnameless/spring-bulk-api/blob/c93947c5b25ec54e2650ff4bdbb23f4e68531952/src/main/java/com/github/wnameless/spring/bulkapi/DefaultBulkApiService.java#L110) when sent without.
e.g :
- I set server.context-path=backend
- I have a WS which url is localhost:8080/backend/service
- I call localhost:8080/backend/bulk
  - Either I use url /backend/service which result in a failure in RoutingPathResolver#findByRequestPathAndMethod
  - Or I use url /service which result in a failure from DefaultBulkApiService#computeUri that creates the url  localhost:8080/service

**Comment by wnameless** [comment]
For now, server.context-path is not supported by spring-bulk-api.
It only computes the paths which reside in annotations such as @RequestMapping.

**Comment by asterion9** [comment]
added support for a shared context path between the bulk service and the targeted endpoints. see #7

**Comment by wnameless** [comment]
Thanks for the patch. Version 0.6.2 has been released. Enjoy it!
