### ISSUE TITLE
When using an exposed port with i.e. docker, that exposed port is used for the operations URL will fail

### ISSUE THREAD

**Issue by vishal-reddy** [wnameless/spring-bulk-api#8]
i have a published port of 8087 from the container but internally it is 8080. I would like to specify the port in a java annotation potentially in EnableBulkApi(port=8080) so the operation requests use that port instead of 8087

**Comment by wnameless** [comment]
Please try version 0.7.0.

The new feature URITransformer should solve your problem.

By providing following code:

@Bean
public URITransformer uriTransformer() {
  
  return new URITransformer() {

    @Override
    public URI transform(URI uri) {
      // Some actions with uri..
      return uri;
    }

};

You can alter the port to 8087 by implementing it.
